### ISSUE TITLE
Confusion about GCClassic download instructions

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#25]
This morning I got an offline question about downloading GC-Classic following the new instructions: http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_GEOS-Chem_source_code_(13.0.0_and_later_versions)#Step_2:_Create_a_new_branch_in_the_GCClassic_folder. 

The `gitk --all` command failed because their ssh instance didn't have XWindows enabled, and they were confused by the steps.

These instructions look like they are setting up a local development copy of GC-Classic. Is that correct? Is branching immediately necessary?

**Comment by yantosca** [comment]
Thanks @LiamBindle.  I think we should have people open a branch so that they won't be tempted to add their own changes to a detached head state.  Most users will be adding their own changes to the model.   Or maybe we can preface that with "skip this step if you just want to run GEOS-Chem out of the box".

I could add a line to the wiki stating that the ssh should have X11 forwarding enabled.  The would have encountered the same error if trying to plot results.

**Comment by yantosca** [comment]
I've just updated the instructions here so that this is more clear:

 - http://wiki.geos-chem.org/Downloading_GEOS-Chem_source_code_(13.0.0_and_later_versions)#Step_5._.28Optional.29_Create_a_new_branch_in_src.2FGEOS-Chem

 - http://wiki.geos-chem.org/Downloading_GEOS-Chem_source_code_(13.0.0_and_later_versions)#Step_6._.28Optional.29_Check_out_the_main_branch_in_src.2FHEMCO

**Comment by yantosca** [comment]
Also 

 - http://wiki.geos-chem.org/Downloading_GEOS-Chem_source_code_(13.0.0_and_later_versions)#Step_2:_.28Optional.29_Create_a_new_branch_in_the_GCClassic_folder

**Comment by LiamBindle** [comment]
@yantosca Sorry, I thought I responded to this thread. Looks good!
