### ISSUE TITLE
Future revision to the "install" step in GEOS-Chem?

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#37]
It is desirable to build the GMAO libraries (GFE libs, and other MAPL dependencies) as subprojects that are nested in the GCHP repo. This minimizes the number of external dependencies in GCHP. Some of those libraries are standalone libraries (particularly the GFE libraries). These libraries are intallable by `make install` which clashes with our use of `make install`. 

Right now our CMakeLists simply comment out `install()` directives that aren't ours. This is simple, and allows us to maintain a workflow that is similar to the GNUMake-based system, but it means our forks diverge from their upstreams. This leads to the question: "How should we put the GEOS-Chem (GCHP or Classic) executable into the run directory?"

Here are some options that come to mind:

#### Keeping things as they are
Comment out `install()` directives that aren't ours. The overall workflow of GCHP/GEOS-Chem Classic stays the same: Clone, create Rundir & build/install (in either order), run. Updating forks is relatively straightforward, but conflicts will happen because our forks have divereged from the upstreams.

#### More canonical workflows: clone, build, install, ... ???
A workflow in which users clone, build, and install GCHP into an "installation" directory would better align with common practices. Here the "installation directory" is not a run directory---this install directory would actually a local directory with software installations. For example, it might look something like this
```
my-software/
  GCHP-13.1/
    bin/gchp
  GCHP-13.2/
    bin/gchp
  pFUnit-1.3/
    bin/
    include/
    lib/
  pFUnit-1.4/
    bin/
    include/
    lib/
  pFlogger-1.2/
    bin/
    include/
    lib/
  pFlogger-1.5/
    bin/
    include/
    lib/
... (and so on) ...
```

To build and install GCHP users would do this
```console
$ git clone https://github.com/geoschem/GCHP
$ cd GCHP
$ git submodule update --init --recursive
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/my-software
$ make -j install
```

This would create an install directory like the one above (if it doesn't already exist). Multiple versions of GCHP and GMAO libraries could live alongside each other. This "install" step also installs all the GMAO libraries into the install directory, but we don't really need to care about these other installations.

This introduces the need for a new mechanism to get `<INSTALL-PREFIX>/GCHP-??.?/bin/gchp` into run directories. Some ideas that come to mind:

1. Run directory creation copies/symlinks the executable from your installations directory to the run directory at the time it's created.
    - Pros: No extra steps. Assuming symlinks, re-building & installing GCHP will update the executable used in run directories that symlink that executable.
    - Cons: Getting the GCHP executable into the run directory is a part of "run directory creation". This limits flexibility (e.g., changing a run directory to use a GNU build rather than an Intel build) and potentially makes the workflow less intuitive because the steps aren't separated into operations that just do one thing.
2. Add a script to the run directory that copies/symlinks the executable. This script would either need an argument, or to prompt the user for the path to that "installations" directory.
    - Pros: Conceptually simple---it's only doing one thing. It's flexible because users could change the linked executable any time.  Also same benefits as 1.
    - Cons: It's a new step, and a new script in the run directory.

After writing this out, I lean towards 2. Seems like it has all the same benefits are 1, but it's also conceptually simpler and cleaner. 

I could make this change as a part of revising the GCHP build system to use the external collaborator support that GMAO has added over the past year. It woulnd't go into 13.1, but more likely 13.2 or 13.3.

I'm curious to hear what you all think. Do you think we should stick with our current workflow for the next while? Or should we update to a more conventional workflow of building and installing?

**Comment by lizziel** [comment]
Thanks @LiamBindle. Some initial thoughts on this I have...

1. We just changed a lot in 13.0. Maybe we should wait for the dust to settle before switching things up again for workflow if it is going to impact users.

2. For GCHP 13 dev a year ago I was building in the source code and then started confusing myself when I was switching branches in the same clone. I ended up rebuilding more frequently than I needed since I wasn't labeling my build directories with the version they built.  I found organizing my run directories by what I was testing and building from each better allowed using the same clone for multiple lines of development. But maybe I didn't give it enough of a chance. How do you handle this problem?

3. If there is a single directory for installs of super-project and some of its dependencies, and each has to have version in the directory name, wouldn't that get unwieldy over time as they accumulate? For example, multiple GCHPs, pFlogger, pFUnit, etc all together. Also, if one of the installs is for an interim commit of say, pFlogger, how would the naming be handled? And how would you know which one went with which version of GCHP? It sounds like it would be ideal for the case of a using a stable version that is static for a long time (which is probably most users), but what about if you have multiple lines of development changing daily?

4. I favor copying the executable over sym linking within the run directory. If you change the target during development then your executable would change too which would prevent reproducibility. This could easily happen unknowingly.

**Comment by LiamBindle** [comment]
Oops, sorry @lizziel, I missed this.

1. Retaining the current workflow means there will be necessary diffs in the CMakeLists. Specifically, GMAO's CMakeLists are set up to "install" libraries like MAPL to the `${CMAKE_INSTALL_PREFIX}`. This means we need to modify the MAPL/GFE install behaviour to use our current workflow.
2. I usually only use one branch per clone (I don't switch between branches in the same repo).
3. For development, I think you would want to set the install prefix to some temporary and local directory (e.g., `./install` in your build directory). The install directory is really just a copy of the executables, libraries, headers, and modules, in a place that is separate from where all the build files are. We can continue to use static linking so we don't have to worry about loading the correct version of e.g. `libpflogger.so`  at runtime because static linking puts the library into the executable.
4. Good point. I think the canonical way to do this would be to generate modulefiles in the install directory so that one would instead load the appropriate version of GCHP like `module load gchp/13.0.2`. For development, we could add a flag that lets you name the installation like `cmake . -DBUILD_NAME="my_drydep"`, and then you do `make install` followed by `module load gchp/13.0.2-my_drydep`
